---
title: "In Progress"
subtitle: ""
author: Aidan Troha - College of Public Health, University of Georgia
date: "`r Sys.Date()`"
format:
  docx:
    toc: false
    number-sections: true
    highlight-style: github
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
# Load necessary packages
library(readr)
library(tidyverse)
```

# Abstract

Introduction: Modeling adolescent behavioral and cognitive outcomes is complicated by the multifaceted nature of neural development, especially during this period of rapid cognitive and behavioral change. Leveraging data obtained from the Adolescent Brain Cognitive Development (ABCD) cohort (N=11,863, ages 9-15, 4 time points), our research uncovered emerging longitudinal patterns of cognitive and behavioral development as well as their relationship to sex and external factors such as social economic status. 
Method: Twenty-five cognitive and behavioral outcomes were selected, and growth curve models were obtained for each using latent growth curve analysis from the `lavaan` package (version 0.6-19) in R (version 4.4.1). Both linear and quadratic growth curves were considered, the criteria for best fitting models were log-likelihood, Akaike information criterion (AIC), Bayesian information criterion (BIC), comparative fit index (CFI), and root mean square error of approximation (RMSEA). The model which had the best combination of the 5 measures was selected as the best performing model. Further, the slope and intercept terms were extracted for each of the 25 models, and the effect size on each slope and intercept term was estimated from four social indices (socio-economic status (SES), area deprivation index (ADI), social vulnerability index (SVI), and child opportunity index (COI)) using mixed-effect models from the `lme4` package (version 1.1-35.3) as random effects and family ID and site ID as fixed effects. 
Results:  Quadratic models fit best for all the behavioral measures and only one of the cognitive measures; conversely, externalizing behaviors revealed improved model fit for the inclusion of a quadratic term but showed insignificant effect size of the quadratic coefficient, indiscriminate of sex, implying that linear modeling of externalizing behaviors is more parsimonious. On average, male and female cognitive trajectories were similar while female behavior trajectories tended to be lower than those for males except for anxiety and somatic problems measures. Of the four social indices, SES demonstrated the best predictive qualities for all measures in this analysis; similarly, COI had a significant effect on all but one of the neurodevelopmental measures tested, indicating that social environment may play a key role in determining cognitive growth trajectories for adolescents. SES was associated with increased cognitive performance and decreased behavioral problems at baseline and, in general, influenced quadratic slope terms of the models.
Conclusion: Results bolster the body of evidence that conclude differences arise in the neurological development of male and female adolescents. Additionally, empirical evidence obtained through this analysis supports further claims that improved social environments are associated with increases in cognitive performance and decreases in behavioral problems. These findings demonstrate that cognitive and behavioral trajectories can be effectively modeled via nonlinear estimation from large longitudinal data and, in doing so, elucidate latent characteristics of neurological development. 

# Introduction

# Methods

# Results

# Discussion

# Acknowledgements

# References

# Appendix