---
title: "Model Building Framework for ABCD Data (Part 2)"
author: "Aidan H. Troha"
date: Sys.date()
output: html_document
---

```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
library(tidymodels)
library(multilevelmod)
```

```{r}
preds <- readRDS("../1 Data/clean_data/Model_Predictions.RData")
data <- readRDS("../1 Data/clean_data/Subject_Ordered_Data.RData")

ses <- read_csv("../1 Data/raw_data/latentfac.csv") %>%
             dplyr::select(!(...1))

adi <- read_csv("../1 Data/raw_data/adi.csv") %>%
       dplyr::select(!(...1))

svi <- read_csv("../1 Data/raw_data/svi.csv") %>%
       dplyr::select(!(...1))

coi <- read_csv("../1 Data/raw_data/coi.csv") %>%
       dplyr::select(!(...1))

for (i in 1:length(preds)) {
    preds[[i]] <- preds[[i]] %>%
                  left_join(ses[,c(1,3)],by="src_subject_id") %>%
                  left_join(coi[,c(1,3)],by="src_subject_id") %>%
                  left_join(adi[,c(1,3)],by="src_subject_id") %>%
                  left_join(svi[,c(1,3)],by="src_subject_id") %>%
                  drop_na()
}
```

```{r}
# Setting the Model Workflow
summary(lmer(i ~ subject_sex + latent_factor_ss_general_ses + reshist_addr1_coi_r_coi_nat + 
                reshist_addr1_adi_wsum + reshist_addr1_svi_tot_20142018 + 
                (1|site_id_l) + (1|rel_family_id),
             preds[[3]]))
summary(lmer(s ~ subject_sex + latent_factor_ss_general_ses + reshist_addr1_coi_r_coi_nat + 
                reshist_addr1_adi_wsum + reshist_addr1_svi_tot_20142018 + 
                (1|site_id_l) + (1|rel_family_id),
             preds[[1]]))
summary(lmer(s ~ subject_sex + latent_factor_ss_general_ses + reshist_addr1_coi_r_coi_nat + 
                reshist_addr1_adi_wsum + reshist_addr1_svi_tot_20142018 + 
                (1|site_id_l) + (1|rel_family_id),
             preds[[1]]))
```

```{r}
fit_mem <- list()
for (i in 1:length(data)) {
    if (gsub("(.*),(.*)","\\2",names(preds)[i]) == "Linear Model") {
        fit_mem[[i]] <- list(lmer(i ~ subject_sex + latent_factor_ss_general_ses +
                                          reshist_addr1_adi_wsum +
                                          reshist_addr1_coi_r_coi_nat + 
                                          reshist_addr1_svi_tot_20142018 +
                                          (1|site_id_l) + (1|rel_family_id),
                                 preds[[i]]),
                                 lmer(s ~ subject_sex + latent_factor_ss_general_ses +
                                          reshist_addr1_adi_wsum +
                                          reshist_addr1_coi_r_coi_nat + 
                                          reshist_addr1_svi_tot_20142018 +
                                          (1|site_id_l) + (1|rel_family_id),
                                 preds[[i]]))
        names(fit_compare[[i]]) <- c("Intercept","1st Order Slope")
    } else if (gsub("(.*),(.*)","\\2",names(preds)[i]) == "Quadratic Model") {
        fit_mem[[i]] <- list(lmer(i ~ subject_sex + latent_factor_ss_general_ses +
                                          reshist_addr1_adi_wsum +
                                          reshist_addr1_coi_r_coi_nat + 
                                          reshist_addr1_svi_tot_20142018 +
                                          (1|site_id_l) + (1|rel_family_id),
                                 preds[[i]]),
                                 lmer(s ~ subject_sex + latent_factor_ss_general_ses +
                                          reshist_addr1_adi_wsum +
                                          reshist_addr1_coi_r_coi_nat + 
                                          reshist_addr1_svi_tot_20142018 +
                                          (1|site_id_l) + (1|rel_family_id),
                                 preds[[i]]),
                                 lmer(q ~ subject_sex + latent_factor_ss_general_ses +
                                          reshist_addr1_adi_wsum +
                                          reshist_addr1_coi_r_coi_nat + 
                                          reshist_addr1_svi_tot_20142018 +
                                          (1|site_id_l) + (1|rel_family_id),
                                 preds[[i]]))
        names(fit_mem[[i]]) <- c("Intercept","1st Order Slope","2nd Order Slope")
    }
    names(fit_mem)[i] <- names(data)[i]
}
```

```{r}
fin_preds <- readRDS("../1 Data/clean_data/Model_Predictions.RData")
for (i in 1:length(preds)) {
    fin_preds[[i]] <- fin_preds[[i]] %>%
                      left_join(ses[,c(1,3)],by="src_subject_id") %>%
                      drop_na(latent_factor_ss_general_ses)
}
fin_fit <- list()
for (i in 1:length(preds)) {
    if (gsub("(.*),(.*)","\\2",names(preds)[i]) == "Linear Model") {
        fin_fit[[i]] <- list(lmer(i ~ subject_sex + latent_factor_ss_general_ses +
                                      (1|site_id_l) + (1|rel_family_id),
                                  preds[[i]]),
                             lmer(s ~ subject_sex + latent_factor_ss_general_ses +
                                      (1|site_id_l) + (1|rel_family_id),
                                  preds[[i]]))
        names(fin_fit[[i]]) <- c("Intercept","1st Order Slope")
    } else if (gsub("(.*),(.*)","\\2",names(preds)[i]) == "Quadratic Model") {
        fin_fit[[i]] <- list(lmer(i ~ subject_sex + latent_factor_ss_general_ses +
                                      (1|site_id_l) + (1|rel_family_id),
                                  preds[[i]]),
                             lmer(s ~ subject_sex + latent_factor_ss_general_ses +
                                      (1|site_id_l) + (1|rel_family_id),
                                  preds[[i]]),
                             lmer(q ~ subject_sex + latent_factor_ss_general_ses +
                                      (1|site_id_l) + (1|rel_family_id),
                                  preds[[i]]))
        names(fin_fit[[i]]) <- c("Intercept","1st Order Slope","2nd Order Slope")
    }
    names(fin_fit)[i] <- names(fin_fit)[i]
}

# Coefficient extraction
coefs <- list()
for (i in 1:length(fin_fit)) {
    if (gsub("(.*),(.*)","\\2",names(preds)[i]) == "Linear Model") {
        coefs[[i]] <- list(summary(fin_fit[[i]][[1]])$coefficients,
                           summary(fin_fit[[i]][[2]])$coefficients)
        names(coefs[[i]]) <- c("Intercept","1st Order Slope")
    } else if (gsub("(.*),(.*)","\\2",names(preds)[i]) == "Quadratic Model") {
        coefs[[i]] <- list(summary(fin_fit[[i]][[1]])$coefficients,
                           summary(fin_fit[[i]][[2]])$coefficients,
                           summary(fin_fit[[i]][[3]])$coefficients)
        names(coefs[[i]]) <- c("Intercept","1st Order Slope","2nd Order Slope")
    }
    names(coefs)[i] <- names(fin_fit)[i]
}
coefs.table <- data.table::rbindlist(coefs,use.names=T,fill=T,idcol="Measure")
```
